project_name: reka

builds:
- env:
  - CGO_ENABLED=0
  binary: reka
  goos:
      - windows
      - darwin
      - linux
  goarch:
    - 386
    - amd64

  ignore:
    - goos: darwin
      goarch: 386

dockers:
  - image_templates:
    - mensaah/{{.ProjectName}}
    goos: linux
    goarch: amd64
    goarm: ''
    dockerfile: Dockerfile
    skip_push: false

archives:
  - name_template: "{{.Binary}}_{{.Os}}_{{.Arch}}"
    format_overrides:
      - goos: windows
        format: zip
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
