// Code generated by "enumer -type=Status ./status.go"; DO NOT EDIT.

//
package resource

import (
	"fmt"
)

const _StatusName = "PendingRunningShuttingDownDestroyedStoppingStoppedError"

var _StatusIndex = [...]uint8{0, 7, 14, 26, 35, 43, 50, 55}

func (i Status) String() string {
	if i < 0 || i >= Status(len(_StatusIndex)-1) {
		return fmt.Sprintf("Status(%d)", i)
	}
	return _StatusName[_StatusIndex[i]:_StatusIndex[i+1]]
}

var _StatusValues = []Status{0, 1, 2, 3, 4, 5, 6}

var _StatusNameToValueMap = map[string]Status{
	_StatusName[0:7]:   0,
	_StatusName[7:14]:  1,
	_StatusName[14:26]: 2,
	_StatusName[26:35]: 3,
	_StatusName[35:43]: 4,
	_StatusName[43:50]: 5,
	_StatusName[50:55]: 6,
}

// StatusString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func StatusString(s string) (Status, error) {
	if val, ok := _StatusNameToValueMap[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Status values", s)
}

// StatusValues returns all values of the enum
func StatusValues() []Status {
	return _StatusValues
}

// IsAStatus returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Status) IsAStatus() bool {
	for _, v := range _StatusValues {
		if i == v {
			return true
		}
	}
	return false
}
