// Code generated by "enumer -type=State ./provider/states.go"; DO NOT EDIT.

//
package resource

import (
	"fmt"
)

const _StateName = "PendingRunningShuttingDownDestroyedStoppingStopped"

var _StateIndex = [...]uint8{0, 7, 14, 26, 35, 43, 50}

func (i State) String() string {
	if i < 0 || i >= State(len(_StateIndex)-1) {
		return fmt.Sprintf("State(%d)", i)
	}
	return _StateName[_StateIndex[i]:_StateIndex[i+1]]
}

var _StateValues = []State{0, 1, 2, 3, 4, 5}

var _StateNameToValueMap = map[string]State{
	_StateName[0:7]:   0,
	_StateName[7:14]:  1,
	_StateName[14:26]: 2,
	_StateName[26:35]: 3,
	_StateName[35:43]: 4,
	_StateName[43:50]: 5,
}

// StateString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func StateString(s string) (State, error) {
	if val, ok := _StateNameToValueMap[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to State values", s)
}

// StateValues returns all values of the enum
func StateValues() []State {
	return _StateValues
}

// IsAState returns "true" if the value is listed in the enum definition. "false" otherwise
func (i State) IsAState() bool {
	for _, v := range _StateValues {
		if i == v {
			return true
		}
	}
	return false
}
