# Config variables for the Reka application. These variables can also be set from environment with
# the reka namespace
# Example:
# name => REKA_NAME
# refreshInterval => REKA_REFRESHINTERVAL
# auth.username => REKA_AUTH_USERNAME

name: reka
# Providers to be enabled for reka
providers:
  - aws
# logPath: /path/to/logs/dir/

# Time to refresh resources in hours
refreshInterval: 4

# web
  # auth:
  #   username: blank   # Can 
  #   password: blank

# If not set defaults to $(pwd)/reka-state.json
StateBackend:
  type: local
  path: /path/to/local/store/state

aws:
#   # Env: AWS_SECRET_ACCESS_KEY
#   secretAccessKey: blank
#   # ENV: AWS_ACCESS_KEY_ID
#   accessKeyID: blank
#   # ENV: AWS_REGION
#   defaultRegion: us-east-2

gcp:
#   projectId: Something

exclude:
  - name: Exclude resources with prod tags in us-east-2
    region: "us-east-2"
    tags:
      env: prod
  - name: Exclude EC2 Instances
    region: "us-east-2"
    resources:
      - aws.ec2

# Rules for stopping, resuming and terminating instances
rules:
  - name: Pause all staging instances on a weekend (staging)
    # Target specific resource types
    target:
      - aws.ec2
      - aws.ebs
    tags:
      env: staging
    condition:
      activeDuration: 
        startTime: "8:00"
        stopTime: "18:00"
        startDay: Monday
        stopDay: Friday
      region: "us-east-2"
  - name: Delete all tests instances older than 24hrs (test)
    tags:
      env: test
      ci: true
    condition:
      terminationPolicy: older than 24hrs
  - name: Nuke all project A instances after Demo october 9th (staging)
    tags:
      env: staging
      project: A
    condition:
      terminationDate: october 9
  - name: Delete all unused instances older than 48hrs (staging)
    tags:
      env: staging
    condition:
      terminationPolicy: unused


timezone: Africa/Lagos
# timezone: UTC+1