on: [push, pull_request]
name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.15.0'
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: go get -v
    - name: check if supported resources list is up to date
      run: |
        go run main.go resources > actual.md
        echo "Supported resources list can be updated by running 'go run main.go resources > docs/supported-resources.md'"
        diff actual.md docs/supported-resources.md
    - name: Test
      run: go test .
